Weight sharing dim
kazukiosawa/asdl pull request #54
Opened 2024-11-20 23:41 UTC by wiseodd

Basically just reverting to the old one.

@runame please review.

@kazukiosawa I would appreciate it if you could merge & update PyPi! Thanks!

2024-11-20 23:55 UTC, runame requested changes

2024-11-20 23:55 UTC, runame commented on pyproject.toml
> +quote-style = "single"
Is there a reason to add ruff here? I assume the whole code base (besides the file modified in this PR) is not formatted with ruff.

2024-11-20 23:55 UTC, runame commented on asdl/gradient.py
> +        grads = torch.cat(grads, dim=1)  # (..., p)
Shouldn't this be `dim=-1`?

2024-12-02 21:51 UTC, wiseodd commented
@runame could you check once more. The requested changes should be resolved.

2024-12-02 22:44 UTC, runame approved these changes
Thanks, LGTM.

2024-12-05 20:41 UTC, kazukiosawa approved these changes
Thank you for the PR! LGTM.

2024-12-05 20:41 UTC, merged